// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoDpL3Cqk1wvQpWgBlJtHmNGXcJZU7--M',
    appId: '1:780836876294:web:4b046a13e5b236113f5387',
    messagingSenderId: '780836876294',
    projectId: 'laundry-lane-a3361',
    authDomain: 'laundry-lane-a3361.firebaseapp.com',
    storageBucket: 'laundry-lane-a3361.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUtBH5_XTnnk1OAuBPmarD4tn-c9JQyWY',
    appId: '1:780836876294:android:8f5b6bc335ba0dbe3f5387',
    messagingSenderId: '780836876294',
    projectId: 'laundry-lane-a3361',
    storageBucket: 'laundry-lane-a3361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY4c6kzVjEHtnk--F622DVTZ3aExLd-Fs',
    appId: '1:780836876294:ios:645f0993922d5aae3f5387',
    messagingSenderId: '780836876294',
    projectId: 'laundry-lane-a3361',
    storageBucket: 'laundry-lane-a3361.firebasestorage.app',
    iosBundleId: 'com.example.laundrylane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY4c6kzVjEHtnk--F622DVTZ3aExLd-Fs',
    appId: '1:780836876294:ios:645f0993922d5aae3f5387',
    messagingSenderId: '780836876294',
    projectId: 'laundry-lane-a3361',
    storageBucket: 'laundry-lane-a3361.firebasestorage.app',
    iosBundleId: 'com.example.laundrylane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoDpL3Cqk1wvQpWgBlJtHmNGXcJZU7--M',
    appId: '1:780836876294:web:b7c22a6cfcce0f833f5387',
    messagingSenderId: '780836876294',
    projectId: 'laundry-lane-a3361',
    authDomain: 'laundry-lane-a3361.firebaseapp.com',
    storageBucket: 'laundry-lane-a3361.firebasestorage.app',
  );
}
